// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACeEB0pnv5Y2mWYC_TU6TBnWI-KXHDfnY',
    appId: '1:808358733660:web:0e8b400e1afcb21fe04399',
    messagingSenderId: '808358733660',
    projectId: 'vagabond-flutter-project',
    authDomain: 'vagabond-flutter-project.firebaseapp.com',
    storageBucket: 'vagabond-flutter-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnqlGZqs5TwjSjvaDgDABuYow-e6dvcXI',
    appId: '1:808358733660:android:e0ac852cc73f3608e04399',
    messagingSenderId: '808358733660',
    projectId: 'vagabond-flutter-project',
    storageBucket: 'vagabond-flutter-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFn05aiI_YOcBfifVqLoJrZmY6NyQPvHM',
    appId: '1:808358733660:ios:dc7a518c661a4bfee04399',
    messagingSenderId: '808358733660',
    projectId: 'vagabond-flutter-project',
    storageBucket: 'vagabond-flutter-project.appspot.com',
    iosBundleId: 'com.example.vagabond',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFn05aiI_YOcBfifVqLoJrZmY6NyQPvHM',
    appId: '1:808358733660:ios:dc7a518c661a4bfee04399',
    messagingSenderId: '808358733660',
    projectId: 'vagabond-flutter-project',
    storageBucket: 'vagabond-flutter-project.appspot.com',
    iosBundleId: 'com.example.vagabond',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyACeEB0pnv5Y2mWYC_TU6TBnWI-KXHDfnY',
    appId: '1:808358733660:web:f16e9ec5347ff327e04399',
    messagingSenderId: '808358733660',
    projectId: 'vagabond-flutter-project',
    authDomain: 'vagabond-flutter-project.firebaseapp.com',
    storageBucket: 'vagabond-flutter-project.appspot.com',
  );
}
